name: Publish Extension

on:
  # Trigger on manual workflow dispatch
  workflow_dispatch:
  # Trigger on new version tags
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Build and package extension
        run: pnpm run package

      - name: Create VSIX package
        run: pnpm run vscode:package

      - name: Get package version
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Publish to VS Code Marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: pnpm run vscode:publish

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Find the generated VSIX file
          vsix_file=$(find . -name "*.vsix" -type f | head -1)

          # Create release
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --notes "Release ${{ github.ref_name }}" \
            --generate-notes \
            "$vsix_file"
